// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qzOnm4Sa0RH7QzDXymDHeO_Lpsq_xrE',
    appId: '1:306904270788:web:89391280fe31e7f7fb8691',
    messagingSenderId: '306904270788',
    projectId: 'madrocketassignment',
    authDomain: 'madrocketassignment.firebaseapp.com',
    storageBucket: 'madrocketassignment.appspot.com',
    measurementId: 'G-DSNKYRCL0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXizN_X6TbpothwXtAgDox1iFH6p1f8o8',
    appId: '1:306904270788:android:c61c3dd8c1891263fb8691',
    messagingSenderId: '306904270788',
    projectId: 'madrocketassignment',
    storageBucket: 'madrocketassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLNli6a9HecgesPC-22nzCsM1JnE7_P4',
    appId: '1:306904270788:ios:be77195b86f80a8efb8691',
    messagingSenderId: '306904270788',
    projectId: 'madrocketassignment',
    storageBucket: 'madrocketassignment.appspot.com',
    iosClientId: '306904270788-dgf62o1bacuvm8qvct8oknhnmckcqdn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.madrocketAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGLNli6a9HecgesPC-22nzCsM1JnE7_P4',
    appId: '1:306904270788:ios:d1527363129ce443fb8691',
    messagingSenderId: '306904270788',
    projectId: 'madrocketassignment',
    storageBucket: 'madrocketassignment.appspot.com',
    iosClientId: '306904270788-llvrvgg7rmkuthqs51ndpkhgpapbe28g.apps.googleusercontent.com',
    iosBundleId: 'com.example.madrocketAssignment.RunnerTests',
  );
}
